# Generated by Django 2.2.14 on 2020-07-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_news_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='delete_tags',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='base_url',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
