# Generated by Django 2.2.14 on 2020-07-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200717_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='content_specific',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='title_specific',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
