# Generated by Django 2.2.14 on 2020-07-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200718_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='img',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
