# Generated by Django 2.2.14 on 2020-08-17 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200718_0543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
