# Generated by Django 2.2.14 on 2020-10-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200930_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='language',
            field=models.IntegerField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
