# Generated by Django 2.2.14 on 2020-11-18 15:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201112_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), blank=True, default=None, max_length=250, null=True, size=None),
        ),
    ]
