# Generated by Django 2.2.14 on 2020-11-20 18:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201118_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='api.Poll'),
        ),
        migrations.AlterField(
            model_name='news',
            name='poll',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='api.Poll'),
        ),
    ]
